query GetAssignedAudits {
	audit(where: { closedAt: { _is_null: true } }, order_by: { updatedAt: asc }) {
		private {
			code
		}
		endAt
		updatedAt
		group {
			path
			captainLogin
			members {
				user {
					login
					avatarUrl
					id
				}
			}
		}
	}
}
