query GetUserGroupsById($userId: Int, $offset: Int, $limit: Int) {
	group_user(
		where: { userId: { _eq: $userId }, accepted: { _eq: true } }
		offset: $offset
		limit: $limit
		order_by: [{ group: { updatedAt: desc } }, { id: desc }]
	) {
		...UserGroupFields
	}
}
