query GetUserGroupsByLogin($userLogin: String, $offset: Int, $limit: Int) {
	group_user(
		where: { userLogin: { _eq: $userLogin }, accepted: { _eq: true } }
		offset: $offset
		limit: $limit
		order_by: [{ group: { updatedAt: desc } }, { id: desc }]
	) {
		...UserGroupFields
	}
}
