fragment Audit on audit {
	grade
	closureType
	closureMessage
	attrs
	auditor {
		id
		login
		avatarUrl
		canAccessPlatform
	}
}

fragment Group on group {
	id
	status
	captain {
		id
		login
	}
	members(where: { accepted: { _eq: true } }) {
		user {
			id
			login
			avatarUrl
			canAccessPlatform
		}
	}
	invitations: members(where: { accepted: { _eq: false } }) {
		user {
			id
			login
			avatarUrl
			canAccessPlatform
		}
	}
	auditors(where: { resultId: { _is_null: true } }) {
		...Audit
	}
	results(order_by: { createdAt: desc }) {
		grade
		id
		createdAt
		audits {
			...Audit
		}
	}
}
